export const OPTIONS = {
  accessory: ['none', 'roundGlasses', 'tinyGlasses', 'shades'],
  body: ['chest', 'breasts'],
  clothing: ['naked', 'shirt', 'dressShirt', 'vneck', 'tankTop', 'dress'],
  clothingColor: ['white', 'blue', 'black', 'green', 'red'],
  eyebrows: ['raised', 'leftLowered', 'serious', 'angry', 'concerned'],
  eyes: [
    'normal',
    'leftTwitch',
    'happy',
    'content',
    'squint',
    'simple',
    'dizzy',
    'wink',
    'heart',
  ],
  facialHair: ['none', 'stubble', 'mediumBeard'],
  graphic: ['none', 'redwood', 'gatsby', 'vue', 'react', 'graphQL'],
  hair: [
    'none',
    'long',
    'bun',
    'short',
    'pixie',
    'balding',
    'buzz',
    'afro',
    'bob',
  ],
  hairColor: ['blonde', 'orange', 'black', 'white', 'brown', 'blue', 'pink'],
  hat: ['none', 'beanie', 'turban'],
  hatColor: ['white', 'blue', 'black', 'green', 'red'],
  lipColor: ['red', 'purple', 'pink', 'turqoise', 'green'],
  mouth: ['grin', 'sad', 'openSmile', 'lips', 'open', 'serious', 'tongue'],
  skinTone: ['light', 'yellow', 'brown', 'dark', 'red', 'black'],
  faceMaskColor: ['white', 'blue', 'black', 'green', 'red'],
} as const;
